#!/usr/bin/env bash
# Print domains and subdomains

print_domain_subdomain () {
    IP=$(dig +short "$1")
    if [ -n "$IP" ]; then
        echo "The subdomain $2 is an A record and points to $IP"
    else
        echo "The subdomain $2 does not have an A record"
    fi
}

if [ "$#" -eq 2 ]; then
    print_domain_subdomain "$2.$1" "$2"
else
    print_domain_subdomain "www.$1" "www"
    print_domain_subdomain "lb-01.$1" "lb-01"
    print_domain_subdomain "web-01.$1" "web-01"
    print_domain_subdomain "web-02.$1" "web-02"
fi
