#!/usr/bin/env bash
# Configures Nginx server so that /redirect_me is redirecting to another page with a 301 status

# Install Nginx if not already installed
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'

# Create a redirection configuration
sh -c 'echo "Hello, World!" > /var/www/html/index.html'
sed -i 'listen 80 default_server/a rewrtie ^/redirect_me https://www.youtube.com/@baebischops permanent;' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo systemctl restart nginx
