#!/usr/bin/env bash
# Configures Nginx server so that /redirect_me is redirecting to another page with a 301 status

# Install Nginx if not already installed
sudo apt-get update
sudo apt-get -y install nginx

# Create a redirection configuration
sudo bash -c 'cat <<EOF >> /etc/nginx/sites-available/default

server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOF'

# Restart Nginx to apply changes
sudo systemctl restart nginx
